import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const cases = sqliteTable('cases', {id:text('id').primaryKey(),owner:text('owner').notNull(),q:text('q').notNull(),tag:text('tag').notNull(),at:text('at').notNull(),a:text('a').notNull(),bt:text('bt').notNull(),b:text('b').notNull(),emoji:text('emoji').notNull(),created:integer('created').notNull(),closes:integer('closes').notNull(),status:text('status').notNull(),story:text('story').notNull().default(''),audience:text('audience').notNull().default('public'),workflow:integer('workflow').notNull().default(0),evidence:text('evidence'),invite:text('invite'),respondent:text('respondent'),duration:integer('duration').notNull()}, t=>[index('cases_owner').on(t.owner),index('cases_status').on(t.status)]);
export const votes = sqliteTable('votes',{caseId:text('case_id').notNull(),userId:text('user_id').notNull(),choice:text('choice').notNull(),at:integer('at').notNull()},t=>[primaryKey({columns:[t.caseId,t.userId]}),index('votes_user').on(t.userId)]);
export const reports = sqliteTable('reports',{caseId:text('case_id').notNull(),userId:text('user_id').notNull(),reason:text('reason').notNull(),at:integer('at').notNull()},t=>[primaryKey({columns:[t.caseId,t.userId]})]);
// La Sala: lo que dice el jurado después de votar. Un comentario por persona
// y caso, sin respuestas, y SECUNDAR en vez de me gusta.
export const comments = sqliteTable('comments',{id:text('id').primaryKey(),caseId:text('case_id').notNull(),userId:text('user_id').notNull(),name:text('name').notNull().default('Jurado'),side:text('side').notNull(),body:text('body').notNull(),at:integer('at').notNull()},t=>[index('comments_case').on(t.caseId),index('comments_author').on(t.caseId,t.userId)]);
export const seconds = sqliteTable('seconds',{commentId:text('comment_id').notNull(),userId:text('user_id').notNull(),at:integer('at').notNull()},t=>[primaryKey({columns:[t.commentId,t.userId]})]);
// El Pulso: un voto por persona y día. El día va como número entero, que es
// como cuenta los días la partida.
export const pulse = sqliteTable('pulse',{day:integer('day').notNull(),userId:text('user_id').notNull(),choice:text('choice').notNull(),at:integer('at').notNull()},t=>[primaryKey({columns:[t.day,t.userId]}),index('pulse_day').on(t.day)]);
