'use client';
import {CreatorClash} from './creator-clash';
import {GrowingTextarea} from './growing-textarea';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,X,Check,CheckCircle2,DoorClosed,DoorOpen,Copy,Share2,Globe,Link2,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {DefenseFields} from './defense-fields';
import {EvidenceField,EvidenceAccess} from './evidence';
import {creationBack} from '@/lib/creation-navigation';
import {categories,validDefenses,type Case} from '@/lib/cases';
export type ZanjaDraft={story:string;evidence:string|null;q:string;tag:string;at:string;a:[string,string,string];bt:string;b:[string,string,string];mode:string;duration:number;audience:'public'|'link';consent:boolean;pendingId?:string;invite?:string};
type Props={onSignIn:()=>void;onBusy:(busy:boolean)=>void;draft:ZanjaDraft;onChange:(d:ZanjaDraft)=>void;cases:Case[];signedIn:boolean;onRefresh:()=>Promise<boolean>;onClose:()=>void;onHome:()=>void;onCase:(id:string)=>void;onReset:()=>void};
export function CreateZanja({onSignIn,onBusy,draft:d,onChange,cases,signedIn,onRefresh,onClose,onHome,onCase,onReset}:Props){
 const remote=cases.find(c=>c.id===d.pendingId);
 const [step,setStep]=useState(d.pendingId?(remote?.status==='ready'?4:3):1),[route,setRoute]=useState<'choose'|'local'>('choose');
 const [direction,setDirection]=useState<'forward'|'back'>('forward');
 const [busy,setBusy]=useState(false),[imageBusy,setImageBusy]=useState(false),[error,setError]=useState(''),[sharing,setSharing]=useState(false),[copied,setCopied]=useState(false),[published,setPublished]=useState<string|null>(null);
 const body=useRef<HTMLDivElement>(null);
 const patch=(field:keyof ZanjaDraft,value:any)=>onChange({...d,[field]:value});
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 useEffect(()=>{body.current?.scrollTo({top:0});setError('');},[step,route,published]);
 useEffect(()=>{if(!d.pendingId||remote?.status!=='waiting')return;const id=setInterval(()=>{if(!document.hidden)onRefresh();},5000);return()=>clearInterval(id);},[d.pendingId,remote?.status,onRefresh]);
 async function send(payload:unknown){const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data:any=await r.json();if(!r.ok)throw Error(data.error||'No se pudo guardar. Inténtalo de nuevo.');return data;}
 function goStep(target:number){setDirection(target>step?'forward':'back');setStep(target);}
 function next(){if(step===1){onChange({...d,q:d.story});goStep(2);}else if(step===2)goStep(3);else goStep(4);}
 function back(){setDirection('back');const target=creationBack(step,route,!!d.pendingId,!!published);if(target==='home')onHome();else if(target==='close')onClose();else if(target==='choose')setRoute('choose');else goStep(target);}

 async function invite(){setBusy(true);setError('');try{const result=await send({action:'create',...d,mode:'invite',audience:'link',deferPublication:true});onChange({...d,mode:'invite',pendingId:result.id,invite:result.invite});await onRefresh();setSharing(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError('');try{const result=await send(d.pendingId?{action:'publish',id:d.pendingId,tag:d.tag,audience:d.audience,duration:d.duration}:{action:'create',...d,mode:'solo'});await onRefresh();setPublished(result.id);onReset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const link=typeof window==='undefined'?'':`${location.origin}/?${published?'case='+published:'invite='+d.invite}`;
 async function copy(){try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setError('No se pudo copiar. Selecciona el enlace y cópialo.');}}
 async function share(){try{if(navigator.share)await navigator.share({title:published?'Una nueva ZANJA':'Tu versión cuenta · ZANJA',text:published?'¿A quién das la razón?':'Escribe tus tres defensas sin ver las de A.',url:link});else await copy();}catch(e){if((e as Error).name!=='AbortError')setError('No se pudo compartir. Puedes copiar el enlace.');}}
 const titles=['¿QUÉ HA PASADO?','Defensa de Bando A','AHORA LE TOCA A B.','¿QUIÉN PUEDE JUZGAR?'];
 const notes=['Cuéntalo con tus palabras. Este es el relato que verán B y el jurado.','El relato ya está listo. Ahora escribe tus tres motivos.','Cada postura merece su espacio. Elige cómo recoger la otra versión.','Decide quién vota y durante cuánto tiempo.'];
 const readyToContinue=step===1?d.story.trim().length>=12&&!imageBusy:step===2?d.q.trim().length>=12&&d.q.trim().length<=1200&&validDefenses(d.a):validDefenses(d.b);
 return <div className="zanja-creator" data-step={step} data-direction={direction}>
 <header className="creator-top"><button className="icon-btn" onClick={back} disabled={busy} aria-label="Volver"><ArrowLeft size={21}/></button><span>CREA TU ZANJA</span><button className="icon-btn" onClick={onClose} disabled={busy} aria-label="Cerrar y conservar borrador"><X size={21}/></button></header>
 <ol className="creator-progress" aria-label="Progreso">{['Cuéntalo','Bando A','Bando B','Jurado'].map((label,i)=><li key={label} className={published||step>i?'done':''} aria-current={!published&&step===i+1?'step':undefined}><span/>{label}</li>)}</ol>
 <div className="creator-body" ref={body}>
 {published?<section className="creator-success"><div className="case-opening" aria-hidden="true"><DoorClosed className="case-door-closed" size={66}/><DoorOpen className="case-door-open" size={66}/><span className="case-open-check"><Check size={20}/></span></div><span className="creator-eyebrow">CASO PUBLICADO</span><DialogTitle>¡YA PUEDE<br/>VOTAR EL JURADO!</DialogTitle><DialogDescription>Las dos posturas ya están listas. Que decida el jurado.</DialogDescription><button className="game-btn yellow" onClick={()=>onCase(published)}>VER EN EL JUZGADO<ArrowRight size={21}/></button><button className="creator-secondary" onClick={()=>setSharing(true)}><Share2 size={18}/>COMPARTIR ZANJA</button><button className="quiet-btn" onClick={onHome}>Volver al inicio</button></section>:<>
 <div className="creator-heading"><span className="creator-eyebrow">PASO {step} DE 4</span><DialogTitle>{step===3&&route==='local'?'Defensa de Bando B':titles[step-1]}</DialogTitle><DialogDescription>{notes[step-1]}</DialogDescription></div>
 <div key={step+'-'+route} className="creator-stage">
 {step===1&&<><label className="creator-label" htmlFor="case-story">El contexto</label><GrowingTextarea id="case-story" className="creator-story" value={d.story} maxLength={1200} rows={5} placeholder="Habíamos quedado a las ocho. Mi amigo avisó diez minutos antes de que llegaría tarde…" onChange={e=>patch('story',e.target.value)}/><div className="creator-input-meta"><span>Sin nombres ni datos personales</span><span>{d.story.length}/1200</span></div><EvidenceField value={d.evidence} onChange={v=>patch('evidence',v)} onBusy={setImageBusy}/></>}
 {step===2&&<><section className="creator-question creator-account" aria-label="Relato del caso"><span className="creator-label">LO QUE HA PASADO</span><p>{d.story||d.q}</p></section><DefenseFields side="a" values={d.a} onChange={v=>patch('a',v)}/></>}

 {step===3&&(d.pendingId?<><CreatorClash ready={remote?.status==='ready'}/><h3 className="creator-subtitle">{remote?.status==='ready'?'LAS DOS VERSIONES, LISTAS.':'INVITACIÓN PREPARADA.'}</h3><p className="creator-help">{remote?.status==='ready'?'B ya ha respondido. Ahora puedes elegir el jurado y publicar.':'B verá la pregunta, el contexto y la prueba, pero no tus defensas. El caso aún no está publicado.'}</p>{remote?.status==='ready'?<button className="game-btn yellow" onClick={()=>goStep(4)}>PREPARAR PUBLICACIÓN<ArrowRight size={20}/></button>:<><button className="game-btn yellow" onClick={()=>setSharing(true)}>ENVIAR INVITACIÓN</button><button className="creator-secondary" onClick={()=>onRefresh()}>COMPROBAR RESPUESTA</button><p className="creator-help">Puedes cerrar. Encontrarás la invitación en Mis zanjas.</p><button className="quiet-btn" onClick={()=>{onReset();goStep(1);setRoute('choose');}}>Empezar otra zanja</button></>}</>:route==='choose'?<><CreatorClash/><div className="creator-route-card"><h3>QUE B LO CUENTE.</h3><p>Envía un enlace. Su defensa se escribirá sin conocer la tuya.</p>{signedIn?<button className="game-btn yellow" disabled={busy} onClick={invite}>{busy?'PREPARANDO…':'ENVIAR INVITACIÓN'}</button>:<button className="game-btn yellow" onClick={onSignIn}>ENVIAR INVITACIÓN</button>}</div><button className="creator-secondary" onClick={()=>{setDirection('forward');patch('mode','solo');setRoute('local');}}>AÑADIR DEFENSA DE B AQUÍ</button><p className="creator-help">Esta segunda opción se identifica como un relato de una sola persona.</p></>:<><div className="creator-question"><span className="creator-label">SOBRE QUÉ VOTARÁN</span><p className="creator-account-text">{d.q}</p></div><EvidenceAccess src={d.evidence}/><DefenseFields side="b" values={d.b} onChange={v=>patch('b',v)}/><p className="creator-help">Representa la postura de B con honestidad. Se mostrará que las dos versiones las ha introducido una sola persona.</p></>)}
 {step===4&&<><div className="creator-question"><span className="creator-label">ASÍ LO VERÁ EL JURADO</span><p className="creator-account-text">{d.q}</p><EvidenceAccess src={d.evidence||remote?.evidenceUrl}/></div><fieldset><legend className="creator-label">¿QUIÉN PUEDE JUZGAR?</legend><RadioGroup className="creator-audience" value={d.audience} onValueChange={v=>patch('audience',v)}>{[['public','Jurado público','Aparece en El Juzgado',Globe],['link','Solo con enlace','Tú eliges con quién compartir',Link2]].map(([value,label,help,Icon]:any)=><label key={value} className={d.audience===value?'selected':''}><RadioGroupItem value={value}/><Icon size={23}/><strong>{label}</strong><small>{help}</small></label>)}</RadioGroup></fieldset><fieldset><legend className="creator-label">TIEMPO PARA VOTAR</legend><RadioGroup className="creator-durations" value={String(d.duration)} onValueChange={v=>patch('duration',Number(v))}>{[[900000,'15 MIN'],[3600000,'1 HORA'],[86400000,'24 H']].map(([value,label])=><label className={d.duration===value?'selected':''} key={value}><RadioGroupItem value={String(value)}/>{label}</label>)}</RadioGroup></fieldset><label className="creator-label" htmlFor="case-topic">TEMA</label><select id="case-topic" value={d.tag} onChange={e=>patch('tag',e.target.value)}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select><p className="creator-help">El reloj empieza al publicar. Los resultados se muestran tras votar o al cerrar el caso. Se necesitan 5 votos para un veredicto.</p></>}
 </div></>}
 {error&&<p className="creator-error" role="alert">{error}</p>}
 </div>
 {!published&&(step<3||step===3&&route==='local'&&!d.pendingId||step===4)&&<footer className="creator-footer">{step===4?!signedIn?<button className="game-btn yellow" onClick={onSignIn}>ENTRAR Y PUBLICAR<ArrowRight size={19}/></button>:<button className="game-btn yellow" disabled={busy} onClick={publish}>{busy?<LoaderCircle className="spin"/>:<>¡AL JUZGADO!<ArrowRight size={21}/></>}</button>:<button className="game-btn yellow" disabled={!readyToContinue||busy} onClick={next}>{step===1?'DARLE FORMA':step===2?'ESTA ES MI DEFENSA':'PREPARAR PUBLICACIÓN'}<ArrowRight size={20}/></button>}</footer>}
 <Dialog open={sharing} onOpenChange={setSharing}><DialogContent className="zanja-dialog creator-share"><DialogTitle>{published?'¡Que entre el jurado!':'Tu turno, bando B.'}</DialogTitle><DialogDescription>{published?'Comparte el caso con quienes quieras que voten.':'Envía este enlace a B. Podrá escribir su versión desde el navegador; necesitará iniciar sesión para enviarla.'}</DialogDescription><label className="creator-label" htmlFor="invitation-link">ENLACE</label><input id="invitation-link" readOnly value={link} onFocus={e=>e.target.select()}/><button className="game-btn yellow" onClick={share}><Share2 size={19}/>COMPARTIR</button><button className="creator-secondary" onClick={copy}><Copy size={18}/>{copied?'ENLACE COPIADO':'COPIAR ENLACE'}</button></DialogContent></Dialog>
 </div>;
}
