'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,X,CheckCircle2,Copy,LoaderCircle} from 'lucide-react';
import {DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {DefenseFields} from './defense-fields';
import {EvidenceAccess} from './evidence';
import {validDefenses,draftDefenses} from '@/lib/cases';
type Props={onSignIn:()=>void;onBusy:(busy:boolean)=>void;invitation:any;error:string;token:string;signedIn:boolean;onClose:()=>void;onHome:()=>void;onSend:(b:[string,string,string])=>Promise<boolean>};
export function InviteResponse({onSignIn,onBusy,invitation:c,error,token,signedIn,onClose,onHome,onSend}:Props){
 const [b,setB]=useState<[string,string,string]>(['','','']),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[sent,setSent]=useState(false),[pending,setPending]=useState(true),[copied,setCopied]=useState(false),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 useEffect(()=>{try{setB(draftDefenses(JSON.parse(localStorage.getItem('zanja-response-'+token)||'[]')));}catch{}setHydrated(true);},[token]);
 useEffect(()=>{if(!hydrated||sent)return;try{localStorage.setItem('zanja-response-'+token,JSON.stringify(b));}catch{}},[b,token,hydrated,sent]);
 async function submit(){setBusy(true);setFailure('');try{setPending(await onSend(b));setSent(true);localStorage.removeItem('zanja-response-'+token);}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 const link=typeof location==='undefined'?'':`${location.origin}/?case=${c?.id}`;
 return <div className="zanja-creator" data-step="response"><header className="creator-top"><button className="icon-btn" onClick={onClose} disabled={busy} aria-label="Volver"><ArrowLeft size={21}/></button><span>TU VERSIÓN CUENTA</span><button className="icon-btn" onClick={onClose} disabled={busy} aria-label="Cerrar"><X size={21}/></button></header><div className="creator-body">
 {sent?<section className="creator-success"><CheckCircle2 size={60}/><DialogTitle>¡TU DEFENSA<br/>ESTÁ LISTA!</DialogTitle><DialogDescription>{pending?'Devuelve el enlace a A para que elija el jurado y publique. El caso todavía no admite votos.':'El caso ya está abierto al jurado.'}</DialogDescription><input readOnly value={link} aria-label="Enlace de vuelta al caso" onFocus={e=>e.target.select()}/><button className="game-btn yellow" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setFailure('Selecciona y copia el enlace de arriba.');}}}><Copy size={18}/>{copied?'ENLACE COPIADO':'COPIAR ENLACE PARA A'}</button><button className="creator-secondary" onClick={onHome}>VOLVER AL INICIO</button></section>:<><div className="creator-heading"><span className="creator-eyebrow">BANDO B · TU TURNO</span><DialogTitle>AHORA,<br/>TU VERSIÓN.</DialogTitle><DialogDescription>Tres motivos propios. Las defensas de A seguirán ocultas mientras escribes.</DialogDescription></div>{error?<p role="alert">{error}</p>:!c?<LoaderCircle className="spin"/>:c.mine?<p className="creator-help">Esta es tu invitación. Envíala a la otra persona para que responda con su cuenta.</p>:c.status!=='waiting'?<p className="creator-help">Esta invitación ya recibió una respuesta o dejó de estar disponible.</p>:<><div className="creator-question"><span className="creator-label">EL RELATO DEL CASO</span><p className="creator-account-text">{c.q}</p>{c.story&&c.story!==c.q&&<details><summary>Leer el contexto aportado por A</summary><p>{c.story}</p></details>}<EvidenceAccess src={c.evidenceUrl}/></div><DefenseFields side="b" values={b} onChange={setB}/><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>El relato representa el desacuerdo. Acepto que A publique esta versión sin datos personales.</span></label></>}</>}
 {failure&&<p className="creator-error" role="alert">{failure}</p>}</div>{!sent&&c?.status==='waiting'&&!c.mine&&<footer className="creator-footer">{signedIn?<button className="game-btn yellow" disabled={!consent||!validDefenses(b)||busy} onClick={submit}>{busy?<LoaderCircle className="spin"/>:<>ENVIAR MI DEFENSA<ArrowRight size={20}/></>}</button>:<button className="game-btn yellow" onClick={onSignIn}>ENTRAR Y ENVIAR<ArrowRight size={20}/></button>}</footer>}</div>;
}
